DROP TABLE ODS.BPCCHMAK;
CREATE TABLE ODS.BPCCHMAK (
SEQ DECIMAL(4,0) DEFAULT 0 NOT NULL,
JRNNO DECIMAL(12,0) DEFAULT 0 NOT NULL,
JRN_SEQ DECIMAL(4,0) DEFAULT 0 NOT NULL,
TX_TM DECIMAL(6,0) DEFAULT 0 NOT NULL,
TX_CD CHAR(7) DEFAULT ' ' NOT NULL,
TX_TYPE CHAR(10) DEFAULT ' ' NOT NULL,
MAKER CHAR(8) DEFAULT ' ' NOT NULL,
CHECKER CHAR(8) DEFAULT ' ' NOT NULL,
FIELD_NAME CHAR(20) DEFAULT ' ' NOT NULL,
OLD_VALUE CHAR(150) DEFAULT ' ' NOT NULL,
NEW_VALUE CHAR(150) DEFAULT ' ' NOT NULL,
)
IN TBS_REPORT_DATA INDEX IN TBS_REPORT_INDEX COMPRESS YES;


DROP TABLE ODS.BPCCHMAK;
CREATE TABLE ODS.BPCCHMAK (
SEQ DECIMAL(4,0) DEFAULT 0 NOT NULL,
JRNNO DECIMAL(12,0) DEFAULT 0 NOT NULL,
JRN_SEQ DECIMAL(4,0) DEFAULT 0 NOT NULL,
TX_TM DECIMAL(6,0) DEFAULT 0 NOT NULL,
TX_CD CHAR(7) DEFAULT ' ' NOT NULL,
TX_TYPE CHAR(10) DEFAULT ' ' NOT NULL,
MAKER CHAR(8) DEFAULT ' ' NOT NULL,
CHECKER CHAR(8) DEFAULT ' ' NOT NULL,
FIELD_NAME CHAR(20) DEFAULT ' ' NOT NULL,
OLD_VALUE CHAR(150) DEFAULT ' ' NOT NULL,
NEW_VALUE CHAR(150) DEFAULT ' ' NOT NULL,
)
IN TBS_REPORT_DATA INDEX IN TBS_REPORT_INDEX COMPRESS YES;


DROP TABLE ODS.BPCCHMAK;
CREATE TABLE ODS.BPCCHMAK (
SEQ DECIMAL(4,0) DEFAULT 0 NOT NULL,
JRNNO DECIMAL(12,0) DEFAULT 0 NOT NULL,
JRN_SEQ DECIMAL(4,0) DEFAULT 0 NOT NULL,
TX_TM DECIMAL(6,0) DEFAULT 0 NOT NULL,
TX_CD CHAR(7) DEFAULT ' ' NOT NULL,
TX_TYPE CHAR(10) DEFAULT ' ' NOT NULL,
MAKER CHAR(8) DEFAULT ' ' NOT NULL,
CHECKER CHAR(8) DEFAULT ' ' NOT NULL,
FIELD_NAME CHAR(20) DEFAULT ' ' NOT NULL,
OLD_VALUE CHAR(150) DEFAULT ' ' NOT NULL,
NEW_VALUE CHAR(150) DEFAULT ' ' NOT NULL,
)
IN TBS_REPORT_DATA INDEX IN TBS_REPORT_INDEX COMPRESS YES;


DROP TABLE ODS.BPCCHMAK;
CREATE TABLE ODS.BPCCHMAK (
SEQ DECIMAL(4,0) DEFAULT 0 NOT NULL,
JRNNO DECIMAL(12,0) DEFAULT 0 NOT NULL,
JRN_SEQ DECIMAL(4,0) DEFAULT 0 NOT NULL,
TX_TM DECIMAL(6,0) DEFAULT 0 NOT NULL,
TX_CD CHAR(7) DEFAULT ' ' NOT NULL,
TX_TYPE CHAR(10) DEFAULT ' ' NOT NULL,
MAKER CHAR(8) DEFAULT ' ' NOT NULL,
CHECKER CHAR(8) DEFAULT ' ' NOT NULL,
FIELD_NAME CHAR(20) DEFAULT ' ' NOT NULL,
OLD_VALUE CHAR(150) DEFAULT ' ' NOT NULL,
NEW_VALUE CHAR(150) DEFAULT ' ' NOT NULL,
)
IN TBS_REPORT_DATA INDEX IN TBS_REPORT_INDEX COMPRESS YES;


